### ISSUE TITLE
[web] 랜딩페이지 접속시 로그인 이동 안내

### ISSUE THREAD

**Issue by Beomi** [woowahan-techcamp/4team_BaeminMap#6]
- 유저 로그인이 필수적이기 때문에 로그인 필요
하지만 사이트 들어오자마지 리다이렉트는 좋지 않은 방법으로 보임.

- 따라서 로그인 유도하는 버튼 같은 모달(?) 만들어두면 좋을것 같다고 생각함

**Comment by smartyjpark** [comment]
미들웨어에서 처리하기로 함
