### ISSUE TITLE
모바일에서 터치 안됨

### ISSUE THREAD

**Issue by Beomi** [woowahan-techcamp/4team_BaeminMap#62]
마커 터치 이벤트가 등록되었는데 모바일 크롬에서는 동작 안함

**Comment by smartyjpark** [comment]
원인
---
모바일에서는 마커에 터치이벤트가 적용하지 않음

해결방안
---
별도의 터치 이벤트 리스너를 등록 =>모바일웹의 경우 정보표현 방식이 다르기 때문에 별도 터치이벤트리스너를 달아줄 필요가 있었음
